import React from 'react';
import { NavLink, Outlet, useLocation } from 'react-router-dom';
import { useSession } from '@/lib/session';
import { initials } from '@/lib/format';
import {
  IconAudit,
  IconDashboard,
  IconLogout,
  IconReports,
  IconRules,
  IconSettings,
  IconUsers,
} from './Icons';

const NAV = [
  { group: 'Overview', items: [{ to: '/', label: 'Dashboard', icon: IconDashboard, end: true }] },
  {
    group: 'Manage',
    items: [
      { to: '/users', label: 'Users', icon: IconUsers },
      { to: '/reports', label: 'Reports', icon: IconReports },
    ],
  },
  {
    group: 'Configure',
    items: [
      { to: '/rules', label: 'Numerology Rules', icon: IconRules },
      { to: '/settings', label: 'App Settings', icon: IconSettings },
      { to: '/audit', label: 'Audit Log', icon: IconAudit },
    ],
  },
];

const TITLES: Record<string, { t: string; s: string }> = {
  '/': { t: 'Dashboard', s: 'Live numbers across the whole app' },
  '/users': { t: 'Users', s: 'Everyone who has signed up' },
  '/reports': { t: 'Reports', s: 'Every reading generated by the engine' },
  '/rules': { t: 'Numerology Rules', s: 'Edit meanings without a redeploy' },
  '/settings': { t: 'App Settings', s: 'Runtime configuration the mobile app reads' },
  '/audit': { t: 'Audit Log', s: 'Every admin action, timestamped' },
};

export default function Layout() {
  const { me, signOut } = useSession();
  const { pathname } = useLocation();

  const head =
    TITLES[pathname] ??
    (pathname.startsWith('/users/')
      ? { t: 'User detail', s: 'Profile and full report history' }
      : pathname.startsWith('/reports/')
        ? { t: 'Report detail', s: 'Everything the engine returned' }
        : { t: 'Admin', s: '' });

  return (
    <div className="shell">
      <aside className="sidebar">
        <div className="brand">
          <img src="/sun-emblem.png" alt="" />
          <div>
            <div className="brand-kicker">DADA'S</div>
            <div className="brand-name">NUMEROLOGY</div>
          </div>
        </div>

        <nav className="nav">
          {NAV.map((group) => (
            <React.Fragment key={group.group}>
              <div className="nav-label">{group.group.toUpperCase()}</div>
              {group.items.map((item) => (
                <NavLink
                  key={item.to}
                  to={item.to}
                  end={(item as any).end}
                  className={({ isActive }) => `nav-item ${isActive ? 'active' : ''}`}
                >
                  <item.icon size={17} />
                  {item.label}
                </NavLink>
              ))}
            </React.Fragment>
          ))}
        </nav>

        <div className="sidebar-foot">
          <div className="who">
            <div className="who-av">{initials(me?.full_name, me?.email)}</div>
            <div style={{ minWidth: 0 }}>
              <div className="who-name">{me?.full_name || 'Admin'}</div>
              <div className="who-role">{me?.role}</div>
            </div>
          </div>
          <button className="btn btn-ghost btn-sm" style={{ width: '100%', marginTop: 8 }} onClick={signOut}>
            <IconLogout size={15} /> Sign out
          </button>
        </div>
      </aside>

      <div className="main">
        <header className="topbar">
          <div>
            <h1>{head.t}</h1>
            {!!head.s && <div className="sub">{head.s}</div>}
          </div>
        </header>
        <div className="content">
          <Outlet />
        </div>
      </div>
    </div>
  );
}
